#compose simplifies control of entire application track, making it easy to manage services, networks, and volumes in a single yaml config file

services:


  api-service:
    build:
      context: .
      dockerfile: services/APIService/Dockerfile
    ports:
      - 8002:8002
    depends_on:
      - collector
      - processor
      - composer
      - scheduler
      - jaeger
    networks:
      - app-network